# https://taskfile.dev

version: '3'


tasks:
  client:
    cmds:
      - go run ./client
  server:
    cmds:
      - go run ./server
  gen-grpc:
    dir: common/proto
    cmds:
      - protoc --go-grpc_out=../chat --go_out=../chat --go_opt=paths=source_relative  --go-grpc_opt=paths=source_relative  ./chat.proto 
  install-protoc:
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      - export PATH="$PATH:$(go env GOPATH)/bin" 